<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipioSeeder extends Seeder
{
    public function run(): void
    {
        $municipios = [
            ['clave' => 1, 'nombre' => 'Acatic'],
            ['clave' => 2, 'nombre' => 'Acatlán de Juárez'],
            ['clave' => 3, 'nombre' => 'Ahualulco de Mercado'],
            ['clave' => 4, 'nombre' => 'Amacueca'],
            ['clave' => 5, 'nombre' => 'Amatitán'],
            ['clave' => 6, 'nombre' => 'Ameca'],
            ['clave' => 7, 'nombre' => 'San Juanito de Escobedo'],
            ['clave' => 8, 'nombre' => 'Arandas'],
            ['clave' => 9, 'nombre' => 'El Arenal'],
            ['clave' => 10, 'nombre' => 'Atemajac de Brizuela'],
            ['clave' => 11, 'nombre' => 'Atengo'],
            ['clave' => 12, 'nombre' => 'Atenguillo'],
            ['clave' => 13, 'nombre' => 'Atotonilco el Alto'],
            ['clave' => 14, 'nombre' => 'Atoyac'],
            ['clave' => 15, 'nombre' => 'Autlán de Navarro'],
            ['clave' => 16, 'nombre' => 'Ayotlán'],
            ['clave' => 17, 'nombre' => 'Ayutla'],
            ['clave' => 18, 'nombre' => 'La Barca'],
            ['clave' => 19, 'nombre' => 'Bolaños'],
            ['clave' => 20, 'nombre' => 'Cabo Corrientes'],
            ['clave' => 21, 'nombre' => 'Casimiro Castillo'],
            ['clave' => 22, 'nombre' => 'Cihuatlán'],
            ['clave' => 23, 'nombre' => 'Zapotlán el Grande'],
            ['clave' => 24, 'nombre' => 'Cocula'],
            ['clave' => 25, 'nombre' => 'Colotlán'],
            ['clave' => 26, 'nombre' => 'Concepción de Buenos Aires'],
            ['clave' => 27, 'nombre' => 'Cuautitlán de García Barragán'],
            ['clave' => 28, 'nombre' => 'Cuautla'],
            ['clave' => 29, 'nombre' => 'Cuquío'],
            ['clave' => 30, 'nombre' => 'Chapala'],
            ['clave' => 31, 'nombre' => 'Chimaltitán'],
            ['clave' => 32, 'nombre' => 'Chiquilistlán'],
            ['clave' => 33, 'nombre' => 'Degollado'],
            ['clave' => 34, 'nombre' => 'Ejutla'],
            ['clave' => 35, 'nombre' => 'Encarnación de Díaz'],
            ['clave' => 36, 'nombre' => 'Etzatlán'],
            ['clave' => 37, 'nombre' => 'El Grullo'],
            ['clave' => 38, 'nombre' => 'Guachinango'],
            ['clave' => 39, 'nombre' => 'Guadalajara'],
            ['clave' => 40, 'nombre' => 'Hostotipaquillo'],
            ['clave' => 41, 'nombre' => 'Huejúcar'],
            ['clave' => 42, 'nombre' => 'Huejuquilla el Alto'],
            ['clave' => 43, 'nombre' => 'Hostotipaquillo'],
            ['clave' => 44, 'nombre' => 'Ixtlahuacán de los Membrillos'],
            ['clave' => 45, 'nombre' => 'Ixtlahuacán del Río'],
            ['clave' => 46, 'nombre' => 'Jalostotitlán'],
            ['clave' => 47, 'nombre' => 'Jamay'],
            ['clave' => 48, 'nombre' => 'Jesús María'],
            ['clave' => 49, 'nombre' => 'Jilotlán de los Dolores'],
            ['clave' => 50, 'nombre' => 'Jocotepec'],
            ['clave' => 51, 'nombre' => 'Juanacatlán'],
            ['clave' => 52, 'nombre' => 'Juchitlán'],
            ['clave' => 53, 'nombre' => 'Lagos de Moreno'],
            ['clave' => 54, 'nombre' => 'Magdalena'],
            ['clave' => 55, 'nombre' => 'Santa María del Oro'],
            ['clave' => 56, 'nombre' => 'Mazamitla'],
            ['clave' => 57, 'nombre' => 'Mexticacán'],
            ['clave' => 58, 'nombre' => 'Mezquitic'],
            ['clave' => 59, 'nombre' => 'Mixtlán'],
            ['clave' => 60, 'nombre' => 'Ocotlán'],
            ['clave' => 61, 'nombre' => 'Ojuelos de Jalisco'],
            ['clave' => 62, 'nombre' => 'Pihuamo'],
            ['clave' => 63, 'nombre' => 'Poncitlán'],
            ['clave' => 64, 'nombre' => 'Puerto Vallarta'],
            ['clave' => 65, 'nombre' => 'Villa Purificación'],
            ['clave' => 66, 'nombre' => 'Quitupan'],
            ['clave' => 67, 'nombre' => 'El Salto'],
            ['clave' => 68, 'nombre' => 'San Cristóbal de la Barranca'],
            ['clave' => 69, 'nombre' => 'San Diego de Alejandría'],
            ['clave' => 70, 'nombre' => 'San Juan de los Lagos'],
            ['clave' => 71, 'nombre' => 'San Juanito de Escobedo'],
            ['clave' => 72, 'nombre' => 'San Julián'],
            ['clave' => 73, 'nombre' => 'San Marcos'],
            ['clave' => 74, 'nombre' => 'San Martín de Bolaños'],
            ['clave' => 75, 'nombre' => 'San Martín Hidalgo'],
            ['clave' => 76, 'nombre' => 'San Miguel el Alto'],
            ['clave' => 77, 'nombre' => 'San Sebastián del Oeste'],
            ['clave' => 78, 'nombre' => 'Santa María de los Ángeles'],
            ['clave' => 79, 'nombre' => 'Santa María del Oro'],
            ['clave' => 80, 'nombre' => 'Sayula'],
            ['clave' => 81, 'nombre' => 'Tala'],
            ['clave' => 82, 'nombre' => 'Talpa de Allende'],
            ['clave' => 83, 'nombre' => 'Tamazula de Gordiano'],
            ['clave' => 84, 'nombre' => 'Tapalpa'],
            ['clave' => 85, 'nombre' => 'San Cristóbal de la Barranca'],
            ['clave' => 86, 'nombre' => 'San Diego de Alejandría'],
            ['clave' => 87, 'nombre' => 'San Juan de los Lagos'],
            ['clave' => 88, 'nombre' => 'San Julián'],
            ['clave' => 89, 'nombre' => 'San Marcos'],
            ['clave' => 90, 'nombre' => 'San Martín de Bolaños'],
            ['clave' => 91, 'nombre' => 'San Martín Hidalgo'],
            ['clave' => 92, 'nombre' => 'San Miguel el Alto'],
            ['clave' => 93, 'nombre' => 'Gómez Farías'],
            ['clave' => 94, 'nombre' => 'San Sebastián del Oeste'],
            ['clave' => 95, 'nombre' => 'Santa María de los Ángeles'],
            ['clave' => 96, 'nombre' => 'Santa María del Oro'],
            ['clave' => 97, 'nombre' => 'Sayula'],
            ['clave' => 98, 'nombre' => 'Tala'],
            ['clave' => 99, 'nombre' => 'Talpa de Allende'],
            ['clave' => 100, 'nombre' => 'Tamazula de Gordiano'],
            ['clave' => 101, 'nombre' => 'Tapalpa'],
            ['clave' => 102, 'nombre' => 'Tecalitlán'],
            ['clave' => 103, 'nombre' => 'Tecolotlán'],
            ['clave' => 104, 'nombre' => 'Techaluta de Montenegro'],
            ['clave' => 105, 'nombre' => 'Tenamaxtlán'],
            ['clave' => 106, 'nombre' => 'Teocaltiche'],
            ['clave' => 107, 'nombre' => 'Teocuitatlán de Corona'],
            ['clave' => 108, 'nombre' => 'Tepatitlán de Morelos'],
            ['clave' => 109, 'nombre' => 'Tequila'],
            ['clave' => 110, 'nombre' => 'Teuchitlán'],
            ['clave' => 111, 'nombre' => 'Tizapán el Alto'],
            ['clave' => 112, 'nombre' => 'Tlajomulco de Zúñiga'],
            ['clave' => 113, 'nombre' => 'Tlaquepaque'],
            ['clave' => 114, 'nombre' => 'Tolimán'],
            ['clave' => 115, 'nombre' => 'Tomatlán'],
            ['clave' => 116, 'nombre' => 'Tonalá'],
            ['clave' => 117, 'nombre' => 'Tonaya'],
            ['clave' => 118, 'nombre' => 'Tonila'],
            ['clave' => 119, 'nombre' => 'Totatiche'],
            ['clave' => 120, 'nombre' => 'Tototlán'],
            ['clave' => 121, 'nombre' => 'Tuxcacuesco'],
            ['clave' => 122, 'nombre' => 'Tuxcueca'],
            ['clave' => 123, 'nombre' => 'Tuxpan'],
            ['clave' => 124, 'nombre' => 'Unión de San Antonio'],
            ['clave' => 125, 'nombre' => 'Unión de Tula'],
        ];

        foreach ($municipios as $m) {
            DB::table('municipios')->insert([
                'nombre' => $m['nombre'],
                'clave' => $m['clave'],
                'clave_inegi' => str_pad($m['clave'], 3, '0', STR_PAD_LEFT),
                'activo' => true,
                'cve_ent' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}